### ISSUE TITLE
ButtplugServer dosen't release devices when the websocket is closed

### ISSUE THREAD

**Issue by blackspherefollower** [metafetish/buttplug-csharp#170]
BLE devices that connect remain connected to the server process even after the ButtplugService has been closed. This means you either need to power-cycle the device or restart the server.

**Comment by blackspherefollower** [comment]
@qdot has found that the original fix is pretty unreliable and is digging into the problem.

**Comment by qdot** [comment]
Yeah, looks like there's an ton of cycles inside ButtplugService (I was totally assuming a cycle collector where I guess there isn't one?), and since those cycles hang off of CLR events sometimes, they're basically glued to the system. We'll need to see if we can sweep through and cycle break enough to free objects quicker.

**Comment by qdot** [comment]
Actually I'm gonna reclose this and open a new one. The work you did here is correct, it /does/ release devices as well as we know how, and I think it'll work fine for serial/usb. We need a Win10 BLE specific bug for this weirdness.
